In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
calendar_summary = pd.read_csv("../calendar_summary.csv")
listings = pd.read_csv("../listings.csv")
listings_summary = pd.read_csv("../listings_summary.csv")
neighbourhoods = pd.read_csv("../neighbourhoods.csv")
reviews = pd.read_csv("../reviews.csv")
reviews_summary = pd.read_csv("../reviews_summary.csv")

In [5]:
listings.isnull().sum()

id                                   0
name                                59
host_id                              0
host_name                           26
neighbourhood_group                  0
neighbourhood                        0
latitude                             0
longitude                            0
room_type                            0
price                                0
minimum_nights                       0
number_of_reviews                    0
last_review                       3908
reviews_per_month                 3914
calculated_host_listings_count       0
availability_365                     0
dtype: int64

In [6]:
listings = listings.drop(listings[["name","host_name","last_review"]],axis=1)

In [7]:
listings

,id,host_id,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
0,2015,2217,Mitte,Brunnenstr. Süd,52.534537,13.402557,Entire home/apt,60,4,118,3.76,4,141
1,2695,2986,Pankow,Prenzlauer Berg Nordwest,52.548513,13.404553,Private room,17,2,6,1.42,1,0
2,3176,3718,Pankow,Prenzlauer Berg Südwest,52.534996,13.417579,Entire home/apt,90,62,143,1.25,1,220
3,3309,4108,Tempelhof - Schöneberg,Schöneberg-Nord,52.498855,13.349065,Private room,26,5,25,0.39,1,297
4,7071,17391,Pankow,Helmholtzplatz,52.543157,13.415091,Private room,42,2,197,1.75,1,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22547,29856708,87555909,Mitte,Brunnenstr. Süd,52.533865,13.400731,Entire home/apt,60,2,0,NaN,1,314
22548,29857108,67537363,Tempelhof - Schöneberg,Schöneberg-Nord,52.496211,13.341738,Shared room,20,1,0,NaN,6,78
22549,29864272,3146923,Pankow,Prenzlauer Berg Südwest,52.531800,13.411999,Entire home/apt,85,3,0,NaN,2,15
22550,29866805,36961901,Mitte,Alexanderplatz,52.520802,13.378688,Private room,99,1,0,NaN,3,6
22551,29867352,177464875,Neukölln,Schillerpromenade,52.473762,13.424447,Private room,45,5,0,NaN,1,21

In [8]:
listings["room_type"].value_counts()

Private room       11534
Entire home/apt    10722
Shared room          296
Name: room_type, dtype: int64

In [9]:
listings = listings.rename(columns={"id": "listing_id"})

In [10]:
listings

,listing_id,host_id,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
0,2015,2217,Mitte,Brunnenstr. Süd,52.534537,13.402557,Entire home/apt,60,4,118,3.76,4,141
1,2695,2986,Pankow,Prenzlauer Berg Nordwest,52.548513,13.404553,Private room,17,2,6,1.42,1,0
2,3176,3718,Pankow,Prenzlauer Berg Südwest,52.534996,13.417579,Entire home/apt,90,62,143,1.25,1,220
3,3309,4108,Tempelhof - Schöneberg,Schöneberg-Nord,52.498855,13.349065,Private room,26,5,25,0.39,1,297
4,7071,17391,Pankow,Helmholtzplatz,52.543157,13.415091,Private room,42,2,197,1.75,1,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22547,29856708,87555909,Mitte,Brunnenstr. Süd,52.533865,13.400731,Entire home/apt,60,2,0,NaN,1,314
22548,29857108,67537363,Tempelhof - Schöneberg,Schöneberg-Nord,52.496211,13.341738,Shared room,20,1,0,NaN,6,78
22549,29864272,3146923,Pankow,Prenzlauer Berg Südwest,52.531800,13.411999,Entire home/apt,85,3,0,NaN,2,15
22550,29866805,36961901,Mitte,Alexanderplatz,52.520802,13.378688,Private room,99,1,0,NaN,3,6
22551,29867352,177464875,Neukölln,Schillerpromenade,52.473762,13.424447,Private room,45,5,0,NaN,1,21

In [11]:
calendar_summary = calendar_summary.drop("price", axis=1)

In [12]:
calendar_summary["available"].value_counts()

f    6430639
t    1800841
Name: available, dtype: int64

In [13]:
listings_summary.head(1)

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,requires_license,license,jurisdiction_names,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,2015,https://www.airbnb.com/rooms/2015,20181107122246,2018-11-07,Berlin-Mitte Value! Quiet courtyard/very central,Great location! 30 of 75 sq meters. This wood...,A+++ location! This „Einliegerwohnung“ is an e...,Great location! 30 of 75 sq meters. This wood...,none,It is located in the former East Berlin area o...,...,t,NaN,NaN,f,f,strict_14_with_grace_period,f,f,4,3.76

In [14]:
summfeat = listings_summary[["id","instant_bookable","is_business_travel_ready","require_guest_phone_verification","require_guest_profile_picture"]]

In [15]:
summfeat = summfeat.rename(columns={"id": "listing_id"})

In [16]:
listings = listings.merge(summfeat, on="listing_id")

In [17]:
listings["instant_bookable"].value_counts()

f    15518
t     7034
Name: instant_bookable, dtype: int64

In [18]:
listings

,listing_id,host_id,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,instant_bookable,is_business_travel_ready,require_guest_phone_verification,require_guest_profile_picture
0,2015,2217,Mitte,Brunnenstr. Süd,52.534537,13.402557,Entire home/apt,60,4,118,3.76,4,141,f,f,f,f
1,2695,2986,Pankow,Prenzlauer Berg Nordwest,52.548513,13.404553,Private room,17,2,6,1.42,1,0,f,f,f,f
2,3176,3718,Pankow,Prenzlauer Berg Südwest,52.534996,13.417579,Entire home/apt,90,62,143,1.25,1,220,t,f,f,f
3,3309,4108,Tempelhof - Schöneberg,Schöneberg-Nord,52.498855,13.349065,Private room,26,5,25,0.39,1,297,f,f,f,f
4,7071,17391,Pankow,Helmholtzplatz,52.543157,13.415091,Private room,42,2,197,1.75,1,26,f,f,f,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22547,29856708,87555909,Mitte,Brunnenstr. Süd,52.533865,13.400731,Entire home/apt,60,2,0,NaN,1,314,f,f,f,f
22548,29857108,67537363,Tempelhof - Schöneberg,Schöneberg-Nord,52.496211,13.341738,Shared room,20,1,0,NaN,6,78,t,f,f,f
22549,29864272,3146923,Pankow,Prenzlauer Berg Südwest,52.531800,13.411999,Entire home/apt,85,3,0,NaN,2,15,f,f,f,f
22550,29866805,36961901,Mitte,Alexanderplatz,52.520802,13.378688,Private room,99,1,0,NaN,3,6,f,f,f,f
22551,29867352,177464875,Neukölln,Schillerpromenade,52.473762,13.424447,Private room,45,5,0,NaN,1,21,f,f,f,f

In [19]:
listings.isna().sum()

listing_id                             0
host_id                                0
neighbourhood_group                    0
neighbourhood                          0
latitude                               0
longitude                              0
room_type                              0
price                                  0
minimum_nights                         0
number_of_reviews                      0
reviews_per_month                   3914
calculated_host_listings_count         0
availability_365                       0
instant_bookable                       0
is_business_travel_ready               0
require_guest_phone_verification       0
require_guest_profile_picture          0
dtype: int64

In [30]:
price0 = listings.loc[listings["price"]==0]
price0
listings = listings.drop(price0.index)
listings.loc[listings["price"]==0]

Empty DataFrame
Columns: [listing_id, host_id, neighbourhood_group, neighbourhood, latitude, longitude, room_type, price, minimum_nights, number_of_reviews, reviews_per_month, calculated_host_listings_count, availability_365, instant_bookable, is_business_travel_ready, require_guest_phone_verification, require_guest_profile_picture]
Index: []

Overall data seems pretty clean, dropped all irrelevant/invalid values, ready to be modelled.
I will just be using listings and calendar_summary already wrangled data.

In [31]:
listings.to_csv("../cleaned/listings.csv", index = False, header=True)

In [32]:
calendar_summary.to_csv("../cleaned/calendar_summary.csv", index = False, header=True)